<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 2_address2</name>
   <tag></tag>
   <elementGuidId>d19563dd-503b-43d8-809b-d7ad03307f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d77a9293-8fdf-4552-981d-5947a6b1522a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd664eb6-6339-401c-b92a-bddb0fe3d12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>156c7484-2ff9-4fa6-a20e-9373f4a98ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28bb06c7-d2ec-4629-9edd-a0dbf6d7cad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>59d253ca-df26-474f-9922-a033c3bad2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address2</value>
      <webElementGuid>f433d539-aa86-4cd8-ac30-4a254e2f6d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address2&quot;)</value>
      <webElementGuid>5dfe7441-fc51-471b-97ee-34df4adebee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address2']</value>
      <webElementGuid>f8347590-d06f-4979-9267-cbeee09d9172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[5]/input</value>
      <webElementGuid>55c8110e-9baa-425c-8888-da171e64fb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]/input</value>
      <webElementGuid>b3d22100-ceb4-4ac8-a382-67a31b819b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address2' and @id = 'address2']</value>
      <webElementGuid>4cbede0a-6079-4205-9821-e15f1cb7cb4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
